// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuc74NZs9AEamk0fqKgXCT3b2a8wcs08I',
    appId: '1:1056368075662:web:2b75fd1ef30c9028593adf',
    messagingSenderId: '1056368075662',
    projectId: 'sportshub-351ab',
    authDomain: 'sportshub-351ab.firebaseapp.com',
    storageBucket: 'sportshub-351ab.appspot.com',
    measurementId: 'G-950EM908GE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCREaY8yVkVXtLwMNhhGJ1qFmAzGwW7wbA',
    appId: '1:1056368075662:android:2ab407d600f08854593adf',
    messagingSenderId: '1056368075662',
    projectId: 'sportshub-351ab',
    storageBucket: 'sportshub-351ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4OqpTlXNRR2q3acLH8TJjo4zJjRqxaN4',
    appId: '1:1056368075662:ios:2fddc883e764315f593adf',
    messagingSenderId: '1056368075662',
    projectId: 'sportshub-351ab',
    storageBucket: 'sportshub-351ab.appspot.com',
    iosBundleId: 'com.example.sportsHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4OqpTlXNRR2q3acLH8TJjo4zJjRqxaN4',
    appId: '1:1056368075662:ios:2fddc883e764315f593adf',
    messagingSenderId: '1056368075662',
    projectId: 'sportshub-351ab',
    storageBucket: 'sportshub-351ab.appspot.com',
    iosBundleId: 'com.example.sportsHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuc74NZs9AEamk0fqKgXCT3b2a8wcs08I',
    appId: '1:1056368075662:web:43a6d4d77a38a936593adf',
    messagingSenderId: '1056368075662',
    projectId: 'sportshub-351ab',
    authDomain: 'sportshub-351ab.firebaseapp.com',
    storageBucket: 'sportshub-351ab.appspot.com',
    measurementId: 'G-DN6NK2TF74',
  );
}
